### ISSUE TITLE
Camera Clamp

### ISSUE THREAD

**Issue by IgnobleGaming** [IgnobleGaming/f-sim#2]
## Classes Involved

Camera
## Issues 

Camera does not stop when the controllable moves to the top left corner, possibly others

**Comment by IgnobleGaming** [comment]
I believe i have this fixed, i need to fix the entity moving out of array bounds (Collision bug) to fully check

Snippet of the code used to fix it
http://screen.keylog.me/URLsGlitch.png

**Comment by IgnobleGaming** [comment]
The only issue i see is that on the south and east side, the map renders too far.  

Screen caps, also pushing the current changes so modifications can be made.
http://screen.keylog.me/LogicalBazaar.png
http://screen.keylog.me/DragonsDraining.png
http://screen.keylog.me/ParsesCrufted.png

**Comment by RaidMax** [comment]
The border clamps for the camera are now working. Collision however, is a mess.

![code sample](http://screen.keylog.me/FirmwareCode.png)
